version: '2'
services:
  moodle:
    image: elaskin/moodle
    links:
      - moodle_db
    ports:
      - "80:80"
    tty: true

  moodle_db:
    image: mysql:latest
    environment:
#      MYSQL_HOST: localhost
#      MYSQL_PORT: 3306
#      MYSQL_DATABASE: moodle
#      MYSQL_ROOT_PASSWORD: moodle
#      MYSQL_USER: moodle
#      MYSQL_PASSWORD: moodle
    ports:
      - "3306:3306"
    volumes:
      - .data/moodledb:/var/lib/mysql
