version: '2'
services:
  moodle:
    image: elaskin/moodle
    links:
      - moodle_db
    ports:
      - "80:80"
    tty: true

  moodle_db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - .data/moodledb:/var/lib/mysql
